### ISSUE TITLE
opEqual fails

### ISSUE THREAD

**Issue by apz28** [rumbu13/decimal#11]
`
    void toFloat(ref Decimal!128 d)
    {
        d = d / 100L;
    }

    Decimal!128 d = 540;
    toFloat(d);
    assert(d == 5.40);

`

**Comment by rumbu13** [comment]
It's not failing. 5.40 is not representable as a floating point value.

In fact internaly, 5.40 is 5.400000095367431640625 (double) or 5.400000095367431640625 (single). 

That's the existential reason of this library, when you want 5.40, you have 5.40.
