### ISSUE TITLE
intel.d: Error: signed integer overflow

### ISSUE THREAD

**Issue by pflagerd** [rumbu13/decimal#8]
OpenSUSE 15.0 x86_64 (64bit)
dmd DMD64 D Compiler v2.088.1
dub DUB version 1.17.0, built on Oct 11 2019
decimal 0.9.1

Attempting to build a small test program with decimal 0.9.1 added/fetched with dub:

Performing "debug" build using /usr/bin/dmd for x86_64.
decimal 0.9.1: building configuration "library"...
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5322,14): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5329,14): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5330,14): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5331,14): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5332,14): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5355,13): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5356,13): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5357,13): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5358,13): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5372,13): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5373,13): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5377,13): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5378,13): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5379,13): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5380,13): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5385,14): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5388,14): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5389,14): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5392,13): Error: signed integer overflow
../../../.dub/packages/decimal-0.9.1/decimal/src/test/intel.d(5393,13): Error: signed integer overflow
/usr/bin/dmd failed with exit code 1.

**Comment by m3m0ry** [comment]
Upon adding decimal to my project i get same error

**Comment by Panke** [comment]
Same here.

**Comment by trikko** [comment]
Same here. Linux + dmd.

**Comment by rumbu13** [comment]
This file was not meant to be included in the unitest (along with ibm.d). If someone can adjust dub.json to exclude these files, it will be nice.
